# Generated by Django 3.0 on 2020-03-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mineriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('organismoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineriaApp.Organismo')),
            ],
        ),
    ]
