# Generated by Django 3.0.5 on 2020-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineriaApp', '0002_auto_20200616_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
