# Generated by Django 3.0.5 on 2020-06-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mineriaApp', '0003_auto_20200616_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
