# Generated by Django 3.0 on 2020-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineriaApp', '0003_aspecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('aspectos', models.ManyToManyField(to='mineriaApp.Aspecto')),
                ('entidades', models.ManyToManyField(to='mineriaApp.Entidad')),
            ],
        ),
    ]
