# Generated by Django 3.0.6 on 2020-09-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineriaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organismo',
        ),
    ]
