# Generated by Django 3.0.6 on 2020-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineriaApp', '0002_delete_organismo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nombre',
            new_name='name',
        ),
    ]
