# Generated by Django 3.0.6 on 2020-11-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineriaApp', '0003_auto_20201106_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cliente',
            new_name='client',
        ),
    ]
